# Generated by Django 4.2.1 on 2023-05-31 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('=', 'assigned'), ('X', 'revoked'), ('O', 'finished')], default='=', max_length=1)),
                ('assignation_date', models.DateTimeField(auto_now_add=True)),
                ('dismissing_date', models.DateTimeField(default=None, null=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('dismissing_date', models.DateTimeField(default=None, null=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('visibility', models.CharField(choices=[('+', 'public'), ('-', 'private')], default='-', max_length=1)),
                ('status', models.CharField(choices=[('+', 'open'), ('-', 'closed')], default='+', max_length=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('closing_date', models.DateTimeField(default=None, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'start_date',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('collaborators', models.ManyToManyField(related_name='roles', through='core.Collaboration', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('priority', models.FloatField(default=0.5)),
                ('visibility', models.CharField(choices=[('+', 'public'), ('-', 'private')], default='-', max_length=1)),
                ('status', models.CharField(choices=[('_', 'created'), ('=', 'assigned'), ('>', 'started'), ('|', 'suspended'), ('?', 'to approve'), ('X', 'terminated')], default='_', max_length=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(default=None, null=True)),
                ('request_date', models.DateTimeField(default=None, null=True)),
                ('end_date', models.DateTimeField(default=None, null=True)),
                ('collaborators', models.ManyToManyField(related_name='tasks', through='core.Assignation', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project')),
            ],
            options={
                'get_latest_by': ['creation_date', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='TaskRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='roles',
            field=models.ManyToManyField(related_name='tasks', through='core.TaskRole', to='core.role'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role'),
        ),
        migrations.AddField(
            model_name='assignation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task'),
        ),
        migrations.AddConstraint(
            model_name='taskrole',
            constraint=models.UniqueConstraint(fields=('task', 'role'), name='unique_task_role'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_task'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('priority__gte', 0), ('priority__lte', 1)), name='priority_range'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_role'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_project'),
        ),
        migrations.AddConstraint(
            model_name='collaboration',
            constraint=models.UniqueConstraint(fields=('collaborator', 'role'), name='unique_collaboration'),
        ),
        migrations.AddConstraint(
            model_name='assignation',
            constraint=models.UniqueConstraint(fields=('task', 'collaborator'), name='unique_assignation'),
        ),
    ]
