# Generated by Django 4.2.1 on 2023-05-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
