# Generated by Django 4.2.1 on 2023-06-05 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_role_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='dismissing_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='dismissing_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='closing_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='request_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('_', 'created'), ('=', 'assigned'), ('>', 'started'), ('?', 'to approve'), ('X', 'terminated')], default='_', max_length=1),
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('outcome', models.CharField(choices=[('+', 'accepted'), ('-', 'rejected')], default='?', max_length=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('closing_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requests_received', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='joinrequest',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver', 'role'), name='unique_request'),
        ),
    ]
