# Generated by Django 4.2.1 on 2023-06-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_assignation_dismissing_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinrequest',
            name='outcome',
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='status',
            field=models.CharField(choices=[('+', 'accepted'), ('-', 'rejected'), ('?', 'pending')], default='?', max_length=1),
        ),
    ]
